"""Add address, city, contact, hours, and picture_url columns to Vendor

Revision ID: a63ed666cb11
Revises: 
Create Date: 2025-01-26 20:17:29.072321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63ed666cb11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('picture_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('picture_url')
        batch_op.drop_column('hours')
        batch_op.drop_column('contact')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
